#define IPSTRLEN 64
#define COMMAND_LENGTH 4
#define MAXLINELEN 1024
#define MAX_FILE_LENGTH 255
#define FILE_NOT_FOUND -1
#define MESSAGE_LIST "LIST"
#define MESSAGE_GET	"GETT"
#define MESSAGE_QUIT "QUIT"
#define FILE_SENDING_ENDED "."

